version: "2"
services:
  postgre:
   image: "postgres:9.2.20-alpine"
   environment:
    - POSTGRES_PASSWORD=p@ssword
    - POSTGRES_USER=postgres
    - POSTGRES_DB=testdb
   expose:
    - "5432"

  pg-dump:
    image: "donttouchmytralala/pgsqldmpcrn:latest"
    environment:
     - CRON_SCHEDULE=*/10 * * * *
     - PGUSER=postgres
     - PGPASSWORD=p@ssword
     - PGDATABASE=testdb
     - PREFIX=dump-cron
     - PGHOST=postgre
    links:
     - postgre 
    volumes:
     - /ivan:/dump
     - /etc/localtime:/etc/localtime
    command: 
     - dump-cron

  pgadmin:
    image: "jacksoncage/phppgadmin:latest"
    environment:
     - POSTGRES_HOST=postgre
     - POSTGRES_PORT=5432
     - POSTGRES_DEFAULTDB=testdb
    volumes:
     - /etc/localtime:/etc/localtime
    ports:
     - "8888:80"
    links:
     - postgre
